import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from .config import Config

class FeatureEngineer:
    def __init__(self):
        self.scaler = MinMaxScaler(feature_range=(0, 1))

    def add_technical_indicators(self, df):
        """Adds RSI, EMA, Bollinger Bands using pure pandas"""
        df = df.copy()

        # =========================
        # 1. RSI (14)
        # =========================
        delta = df["close"].diff()

        gain = delta.where(delta > 0, 0.0)
        loss = -delta.where(delta < 0, 0.0)

        avg_gain = gain.rolling(window=14).mean()
        avg_loss = loss.rolling(window=14).mean()

        rs = avg_gain / avg_loss
        df["RSI"] = 100 - (100 / (1 + rs))

        # =========================
        # 2. EMA (20)
        # =========================
        df["EMA_20"] = df["close"].ewm(span=20, adjust=False).mean()

        # =========================
        # 3. Bollinger Bands (20, 2)
        # =========================
        sma_20 = df["close"].rolling(window=20).mean()
        std_20 = df["close"].rolling(window=20).std()

        df["BBL_20_2.0"] = sma_20 - (2 * std_20)
        df["BBM_20_2.0"] = sma_20
        df["BBU_20_2.0"] = sma_20 + (2 * std_20)

        # Drop NaN values generated by indicators
        df.dropna(inplace=True)

        return df

    def prepare_lstm_data(self, df):
        """Scales data and creates 3D sequences for LSTM"""
        # Fit scaler on the base features
        scaled_data = self.scaler.fit_transform(df[Config.FEATURE_COLS])
        
        X, y = [], []
        # Create sequences
        for i in range(Config.SEQ_LEN, len(scaled_data)):
            X.append(scaled_data[i-Config.SEQ_LEN:i])
            y.append(scaled_data[i, 3]) # Index 3 is 'close'
            
        return np.array(X), np.array(y), scaled_data

    def prepare_lgbm_features(self, df, lstm_predictions):
        """
        Combines Technical Indicators with LSTM Predictions.
        We must slice the dataframe to match LSTM's output size.
        """
        # LSTM consumes the first SEQ_LEN rows, so LightGBM must skip them too
        # We also skip the last row if we are training (because we don't have target for tomorrow yet)
        
        # Select Technical Columns (Drop OHLCV, keep indicators)
        ignore_cols = Config.FEATURE_COLS
        indicators = df.drop(columns=ignore_cols).iloc[Config.SEQ_LEN:]
        
        # Ensure lengths match
        min_len = min(len(indicators), len(lstm_predictions))
        indicators = indicators.iloc[:min_len]
        lstm_predictions = lstm_predictions[:min_len]
        
        # Concatenate
        X_lgbm = np.hstack((indicators.values, lstm_predictions))
        return X_lgbm