name: Daily Stock Bot

on:
  schedule:
    # Runs at 22:30 UTC (Market Closed)
    - cron: '30 22 * * 1-5'
  workflow_dispatch: # Allows manual click

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ALLOWS SAVING DATA BACK TO REPO
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run AI Pipeline
        env:
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
        run: python main.py

      - name: Commit & Push Results
        run: |
          git config --global user.name "StockBot"
          git config --global user.email "bot@noreply.github.com"
          git add data/*.csv models/* latest_predictions.csv
          git commit -m "Auto: Daily Update" || echo "No changes to commit"
          git push